### ISSUE TITLE
Problem with the 'mix' method

### ISSUE THREAD

**Issue by NookLook2014** [omarfoq/FedEM#3]
In th aggregator.py, for the method "mix" in class CentralizedAggregator(Aggregator). I found that the average_learners method takes all clients as input rather than the sampled clients. Is that reasonable?  Since clients are sampled each round, i believe it should be better to average thosed sampled clients, then update the averaged global model to all clients.

    def mix(self):
        self.sample_clients()

        for client in self.sampled_clients:
            client.step()

        for learner_id, learner in enumerate(self.global_learners_ensemble):
            learners = [client.learners_ensemble[learner_id] for client in **self.clients**]
            average_learners(learners, learner, weights=self.clients_weights)

**Comment by omarfoq** [comment]
Hello, 

Thank you for your question. I think this issue is similar to #1. Please let me know if  #1 does not answer your question. 

I also want to add that directly performing the weighted average of the sampled clients with the initial weights is not correct in general, instead you need to reweight the clients as done in [(Li et al., 2019, Table~1)](https://arxiv.org/pdf/1907.02189.pdf) for example. 

I hope this answers your question. Please let me know if I am missing something.

**Comment by NookLook2014** [comment]
Ok, thanks for your reply
